# base image
FROM alpine:3.7

# set vault version
ENV VAULT_VERSION 1.2.3

# create a new directory
RUN mkdir /vault

# download dependencies
RUN apk --no-cache add \
      bash \
      ca-certificates \
      curl \
      wget

# download and set up vault in /vault
RUN wget --quiet --output-document=/tmp/vault.zip https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip && \
    unzip /tmp/vault.zip -d /vault && \
    rm -f /tmp/vault.zip && \
    chmod +x /vault

# update PATH
ENV PATH="PATH=$PATH:$PWD/vault"

# add the vault initial configuration script
COPY ./setup_files/configure_vault.sh /vault

CMD [ "/vault/configure_vault.sh" ] 
