version: '2'

services:
  my_vault:
    build:
      context: .
      dockerfile: Dockerfile-Vault
    ports:
      - '8200:8200'

  vault_setup:
    build:
      context: .
      dockerfile: Dockerfile-VaultSetup
    environment:
      VAULT_ADDR: http://my_vault:8200
