version: '3.1'

services:
  mysql:
    image: mysql:5.7
    hostname: dswsql
    environment:
      MYSQL_DATABASE: dswdbaaa
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: abc123
      #    volumes:
      # - data-mysql:/var/lib/mysql


  create_database:
    build:
      context: .

volumes:
  dat-mysql:
    driver: local
