version: '2'

services:
  mysql:
    hostname: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - olidb-data:/var/lib/mysql:rw

  my_app:
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  olidb-data:
