version: '3'

services:
  mysql:
    #image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'mysql_db_eric'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'abc123'
    container_name: mysql_container
    #command: mysql -uroot -pabc123 -Bse "CREATE DATABASE IF NOT EXISTS mysql_db_eric_3"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_vol:/var/lib/mysql
    build:
      context: .
      dockerfile: mysql_docker
    command: --init-file /home/app/mysql_check.sql

volumes:
  mysql_vol:
