FROM ubuntu:16.04

LABEL "com.example.vendor"="ACME Incorporated"

LABEL maintainer="mike"
LABEL build_id="234"
LABEL build_url="http://buildserver/jenkins/job/MyJobName/666/"

CMD ["sleep", "1000"]

