apiVersion: v1
kind: Pod
metadata:
  name: green-vault-setup
  namespace: green
spec:
  containers:
    - image: alpine
      name: green-vault-setup
      command: ["/bin/sh", "-c", "/usr/local/bin/configure_vault.sh"]
#      command: ["/bin/sh", "-c", "sleep 600"]
      env:
      - name: VAULT_ADDR
        value: http://green-vault:8200
      volumeMounts:
      - name: green-vault-volume
        mountPath: /usr/local/bin
  volumes:
    - name: green-vault-volume
      configMap:
        name: vault-setup-script
        defaultMode: 0777
  restartPolicy: Never

