apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - port: 80
  selector:
    app: nginx
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: nginx
        volumeMounts:
        - name: nginx-persistent-storage
          mountPath: /usr/share/nginx/html
      - image: debian
        name: nginx-deploy-index
        volumeMounts:
        - name: nginx-persistent-storage
          mountPath: /pod-data
        command: ["/bin/bash"]
        args: ["-c", "echo This is Prasanth Page > /pod-data/index.html"]
      volumes:
      - name: nginx-persistent-storage
        hostPath:
          path: /Users/prasanth.sasidharan/solid-telegram/solid-telegram/kubernetes/prasanth/exercises
          type: Directory
