#
#

vault.zip:
	wget https://releases.hashicorp.com/vault/1.2.3/vault_1.2.3_linux_amd64.zip -O vault.zip
	sha256sum vault.zip | grep fe15676404aff35cb45f7c957f90491921b9269d79a8f933c5a36e26a431bfc4asdasdfasdf


all:
	@echo "Makefile needs your attention"


# vim:ft=make
#
