---
# tasks file for roles/jenkins
- name: install default-jre
  package:
    name: default-jre
    state: present

- name: Download Jenkins war file
  get_url:
    url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
    dest: /usr/local/etc
    mode: '0440'


- name: Template a file to /etc/systemd/system/jenkins.service
  template:
    src: myTemplate.yml
    dest: /etc/systemd/system/jenkins.service
  notify:
    - restart jenkins service 
