apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - port: 80
  selector:
    app: nginx
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: debian
        name: html-demo-container
        command: ["/bin/sh"]
        args: ["-c", "echo Hello from the debian container > /html/index.html"]
        volumeMounts:
        - name: test-exercise
          mountPath: /html
      - image: nginx
        name: nginx
        volumeMounts:
        - name: test-exercise
          mountPath: /usr/share/nginx/html
      volumes:
      - name: test-exercise
        emptyDir: {}
