version: '2'

services:
  mysql:
    image: mysql:5.7
    hostname: dsw-sql-server
    environment:
      MYSQL_DATABASE: 'dswdbxxx'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: abc123
    volumes:
            - data-mysql:/var/lib/mysql


  create_database:
    build:
      context: .
      dockerfile: databasecreate


  my_app:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: my-hostname
    container_name: my_node_app
    ports:
      - '8080:8080'

volumes:
  data-mysql:
    driver: local
