version: '2'

services:
  mysql:
    image: mysql:5.7
    hostname: dsw-sql-server
    environment:
      MYSQL_DATABASE: 'dswdbyyy'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: abc123
    volumes:
            - data-mysql:/var/lib/mysql


  create_database:
    build:
      context: .
      dockerfile: databasecreate


volumes:
  data-mysql:
    driver: local
