version: '2'
volumes:
  erik-new-volume: {}
services:
  mysql:
    image: mysql:5.7
    volumes:
      - erik-new-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'abc123'
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      #container-name: erik-web-container
    ports:
      - 8080
